project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    # - "!sessions/additional_material/02_quarto/"
    - "!sessions/additional_material/11_efficient-r-2/"
    - "!slides/efficient-R.qmd"

  resources:
    - "slides/slides_pdf/*.pdf"

website:
  page-navigation: true
  repo-url: "https://github.com/selinaZitrone/tools_and_tips"
  site-url: "https://selinazitrone.github.io/tools_and_tips/"
  repo-actions: [edit, issue]
  repo-branch: main
  title: "Scientific workflows: Tools and Tips 🛠️"
  description: "A lecture series by Selina Baldauf"
  favicon: style/favicon.svg

  page-footer:
    left: "© 2023–2026 [Selina Baldauf](mailto:selina.baldauf@fu-berlin.de) · CC BY 4.0"
    right: "Website built with [Quarto](https://quarto.org/)"

  navbar:
    pinned: true
    right:
      - icon: github
        href: https://github.com/selinaZitrone/tools_and_tips


format:
  html:
    embed-resources: true
    theme:
      light: [flatly, style/theme-light.scss, style/theme.scss]
      dark: [darkly, style/theme-dark.scss, style/theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    freeze: auto



