project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!sessions/additional_material/02_quarto/"
    - "!slides/efficient-R.qmd"

  resources:
    - "slides/*.pdf"
    - "slides/*.html"

website:
  page-navigation: true
  repo-url: "https://github.com/selinaZitrone/tools_and_tips"
  site-url: "https://selinazitrone.github.io/tools_and_tips/"
  repo-actions: [edit, issue]
  repo-branch: main
  title: "Scientific workflows: Tools and Tips 🛠️"
  description: "A lecture series by Selina Baldauf"

  page-footer:
    left: "Copyright © 2023 [Selina Baldauf](mailto:selina.baldauf@fu-berlin.de), CC BY 4.0"
    right: "Website built with [Quarto](https://quarto.org/)"

  navbar:
    pinned: true
    right:
      - text: Sessions
        menu:
          - text: 01 - What they forgot to teach you about R
            href: sessions/01_what_they_forgot.qmd
          - text: 02 - Reproducible documents with Quarto
            href: sessions/02_quarto.qmd
          - text: 03 - Version control with Git
            href: sessions/03_git.qmd
          - text: 04 - Research compendia as R packages
            href: sessions/04_research_compendia.qmd
          - text: 05 - Effective digital notetaking with Obsidian
            href: sessions/05_obsidian.qmd
          - text: 06 - Efficient R
            href: sessions/06_efficient_r.qmd
          - text: 07 - AI tools in programming
            href: sessions/07_ai_tools.qmd
          - text: 08 - Tidyverse introduction
            href: sessions/08_tidyverse.qmd
          - text: 09 - Data visualization
            href: sessions/09_data_visualisation.qmd
      - icon: github
        href: https://github.com/selinaZitrone/lecture_series


format:
  html:
    embed-resources: true
    theme:
      light: [flatly, style/theme.scss]
      dark: [darkly, style/theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap



