## Lecture series

### Description:

Early-career researchers understand the importance of digital tools for processing data, managing workflows, and enhancing efficiency. However, they often lack time to discover new tools and improve their workflows. In this lecture series we will explore a diverse range of topics, including R code quality and efficiency, reproducible document creation, version control with Git, literature management, and academic note taking. You'll learn practical tips and tricks that can help you optimize your research workflow and increase your productivity.

### Organization:

📅 Every 3rd Thursday 🕓 4-5 p.m. 📍 Webex


If you don't want to miss a lecture:<br>
Check out the [official lecture website](https://www.bcp.fu-berlin.de/en/graduiertenzentrum/promovierende/veranstaltungen/workshops/lecture-SB/index.html) and [subscribe to the mailing list](https://lists.fu-berlin.de/listinfo/toolsAndTips) to get the link to
the lecture meeting.

For any questions, feedback or topic suggestions [send me an email](mailto:selina.baldauf@fu-berlin.de)

### Material

On this website, you can find all slides and additional resources for lectures:

- 2023-04-20: [What they forgot to teach you about R](sessions/01_what_they_forgot.html)
- 2023-05-11: [Reproducible documents with Quarto](sessions/02_quarto.html)
- 2023-06-15: [Introduction to verion control with Git](sessions/03_git.html)
- 2023-07-20: [Research compendia as R packages](sessions/04_research_compendia.html)
- 2023-10-19: [Effective digital notetaking with Obsidian](sessions/05_obsidian.html)
- 2023-11-16: [Efficient R](sessions/06_efficient_r.html)
- 2024-01-18: [AI tools in programming](sessions/07_ai_tools.html)
- 2024-02-15: [Introduction to the tidyverse](sessions/08_tidyverse.html)
- 2025-04-17: [Clear figures, stronger stories](sessions/09_data_visualisation.html)

I try to regularly upload recordings of the lectures on Youtube. The videos are
linked on the respective topic pages. You can also find the entire [playlist on Youtube](https://youtube.com/playlist?list=PLK1lYQFwxAYeh5pAmCcrlUHCEROQiLI9f&si=mOcqXP5AtB7owg-9)

